"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let placesToVisit = ["Berlin", "Tokyo", "New York", "Rome", "Canberra"];
console.log(`Place I did like to visit`);
console.log(placesToVisit);
let sortedPlaces = placesToVisit.slice().sort();
console.log(`Places in Alphabatial Order => [${sortedPlaces}]`);
console.log(`Places in original order => [${placesToVisit}]`);
let reverseOrder = placesToVisit.slice().reverse();
console.log(`Reversed order => [${reverseOrder}]`);
console.log(`Places in original order => [${placesToVisit}]`);
let reverseOrder2 = placesToVisit.reverse();
console.log(`Reversed order of places => [${reverseOrder2}]`);
let reverseOrder3 = placesToVisit.reverse();
console.log(`Reversed to original order of places => [${reverseOrder3}]`);
let sortedPlaces1 = placesToVisit.sort();
console.log(`Places in Alphabatial Order => [${sortedPlaces1}]`);
let reverseOrder4 = placesToVisit.reverse();
console.log(`Reversed to original order of places => [${reverseOrder4}]`);
